pub mod begin_end_alignment;
pub mod empty_lines;
pub mod end_alignment;
pub mod indentation_consistency;
pub mod indentation_style;
pub mod indentation_width;
pub mod leading_empty_lines;
pub mod trailing_empty_lines;
pub mod trailing_whitespace;
