pub mod layout;
pub mod lint;
mod loader;
mod macros;
pub(crate) mod serde_helpers;
mod yaml;

pub use layout::*;
pub use loader::{LoadError, load_rubocop_yaml, parse_rubocop_yaml};
pub use yaml::{AllCopsConfig, InheritFrom, RubocopYaml};

/// The main configuration struct.
#[derive(Debug, Clone, Default)]
pub struct Config {
    /// Layout cop-specific configurations.
    pub layout: layout::LayoutConfig,
    /// Lint cop-specific configurations.
    pub lint: lint::LintConfig,
}

// Note: Config::from_rubocop_yaml is generated by define_cops! macro in yaml.rs
